/**
 * Foundation Generators
 *
 * Deterministic generation of typography, shadow, and motion tokens from seeds.
 * These complement the color system to form complete design foundations.
 */

import {
  type TypographySeeds,
  type TypographyTokens,
  type ShadowSeeds,
  type ShadowTokens,
  type MotionTokens,
  type FoundationTokens,
  TYPOGRAPHY_RATIOS,
  DEFAULT_TYPOGRAPHY_SEEDS,
  DEFAULT_SHADOW_SEEDS,
  MOTION_TOKENS,
} from '../../types/tailwindPalette';

export type { FoundationTokens };

// =============================================================================
// Typography Scale Generator
// =============================================================================

/**
 * Generate typography tokens from seeds using modular scale
 *
 * The scale is generated by multiplying/dividing the base size by the ratio:
 * - Larger sizes: base × ratio^n
 * - Smaller sizes: base ÷ ratio^n
 */
export function generateTypographyTokens(
  seeds: TypographySeeds = DEFAULT_TYPOGRAPHY_SEEDS
): TypographyTokens {
  const base = seeds.baseFontSize ?? 16;
  const ratio = TYPOGRAPHY_RATIOS[seeds.scaleRatio];
  const lineHeightBody = seeds.lineHeightBody ?? 1.5;
  const lineHeightHeading = seeds.lineHeightHeading ?? 1.2;

  // Generate scale (in rem, relative to 16px root)
  const toRem = (px: number) => `${(px / 16).toFixed(3).replace(/\.?0+$/, '')}rem`;

  return {
    // Smaller than base
    fontSizeXs: toRem(base / (ratio * ratio)),      // base ÷ ratio²
    fontSizeSm: toRem(base / ratio),                 // base ÷ ratio

    // Base
    fontSizeBase: toRem(base),                       // base (1rem)

    // Larger than base
    fontSizeLg: toRem(base * ratio),                 // base × ratio
    fontSizeXl: toRem(base * ratio * ratio),         // base × ratio²
    fontSize2xl: toRem(base * Math.pow(ratio, 3)),   // base × ratio³
    fontSize3xl: toRem(base * Math.pow(ratio, 4)),   // base × ratio⁴
    fontSize4xl: toRem(base * Math.pow(ratio, 5)),   // base × ratio⁵

    // Line heights
    lineHeightTight: lineHeightHeading,
    lineHeightNormal: lineHeightBody,
    lineHeightRelaxed: lineHeightBody + 0.25,
  };
}

/**
 * Convert TypographyTokens to TypographyChoices format
 * Used for backward compatibility with transformTypographyToNodes
 */
export function typographyTokensToChoices(
  tokens: TypographyTokens,
  seeds: TypographySeeds = DEFAULT_TYPOGRAPHY_SEEDS
): {
  typeStack: {
    display: { fontSize: string; lineHeight: string; fontWeight: string; letterSpacing: string };
    h1: { fontSize: string; lineHeight: string; fontWeight: string; letterSpacing: string };
    h2: { fontSize: string; lineHeight: string; fontWeight: string; letterSpacing: string };
    h3: { fontSize: string; lineHeight: string; fontWeight: string; letterSpacing: string };
    body: { fontSize: string; lineHeight: string; fontWeight: string };
    bodyLarge: { fontSize: string; lineHeight: string; fontWeight: string };
    bodySmall: { fontSize: string; lineHeight: string; fontWeight: string };
    caption: { fontSize: string; lineHeight: string; fontWeight: string };
    label: { fontSize: string; lineHeight: string; fontWeight: string; textTransform: string };
    code: { fontSize: string; lineHeight: string; fontFamily: string };
  };
  reasoning: string;
  baseFont: { family: string; fallback: string };
  scale: { rhythm: { grid: number; round: string } };
} {
  const tight = String(tokens.lineHeightTight);
  const normal = String(tokens.lineHeightNormal);

  return {
    typeStack: {
      display: { fontSize: tokens.fontSize4xl, lineHeight: tight, fontWeight: '700', letterSpacing: '-0.02em' },
      h1: { fontSize: tokens.fontSize3xl, lineHeight: tight, fontWeight: '700', letterSpacing: '-0.01em' },
      h2: { fontSize: tokens.fontSize2xl, lineHeight: tight, fontWeight: '600', letterSpacing: '-0.01em' },
      h3: { fontSize: tokens.fontSizeXl, lineHeight: tight, fontWeight: '600', letterSpacing: '0' },
      body: { fontSize: tokens.fontSizeBase, lineHeight: normal, fontWeight: '400' },
      bodyLarge: { fontSize: tokens.fontSizeLg, lineHeight: normal, fontWeight: '400' },
      bodySmall: { fontSize: tokens.fontSizeSm, lineHeight: normal, fontWeight: '400' },
      caption: { fontSize: tokens.fontSizeXs, lineHeight: normal, fontWeight: '400' },
      label: { fontSize: tokens.fontSizeSm, lineHeight: tight, fontWeight: '500', textTransform: 'none' },
      code: { fontSize: tokens.fontSizeSm, lineHeight: normal, fontFamily: 'ui-monospace, monospace' },
    },
    reasoning: `Typography scale generated from ${seeds.scaleRatio} ratio (${TYPOGRAPHY_RATIOS[seeds.scaleRatio]})`,
    baseFont: { family: 'system-ui', fallback: '-apple-system, sans-serif' },
    scale: { rhythm: { grid: 8, round: 'nearest' } },
  };
}

/**
 * Generate typography CSS variables
 */
export function generateTypographyCSS(
  tokens: TypographyTokens,
  indent: string = '  '
): string[] {
  return [
    '',
    `${indent}/* =========================================================`,
    `${indent} * Typography Scale`,
    `${indent} * ========================================================= */`,
    '',
    `${indent}--font-size-xs: ${tokens.fontSizeXs};`,
    `${indent}--font-size-sm: ${tokens.fontSizeSm};`,
    `${indent}--font-size-base: ${tokens.fontSizeBase};`,
    `${indent}--font-size-lg: ${tokens.fontSizeLg};`,
    `${indent}--font-size-xl: ${tokens.fontSizeXl};`,
    `${indent}--font-size-2xl: ${tokens.fontSize2xl};`,
    `${indent}--font-size-3xl: ${tokens.fontSize3xl};`,
    `${indent}--font-size-4xl: ${tokens.fontSize4xl};`,
    '',
    `${indent}--line-height-tight: ${tokens.lineHeightTight};`,
    `${indent}--line-height-normal: ${tokens.lineHeightNormal};`,
    `${indent}--line-height-relaxed: ${tokens.lineHeightRelaxed};`,
  ];
}

// =============================================================================
// Shadow Scale Generator
// =============================================================================

/**
 * Shadow intensity multipliers
 */
const SHADOW_INTENSITY_MULTIPLIERS = {
  none: 0,
  subtle: 0.5,
  medium: 1,
  dramatic: 1.5,
};

/**
 * Base shadow definitions (at medium intensity, neutral, soft)
 */
const BASE_SHADOWS = {
  xs: { y: 1, blur: 2, spread: 0, opacity: 0.05 },
  sm: { y: 2, blur: 4, spread: 0, opacity: 0.06 },
  md: { y: 4, blur: 8, spread: -1, opacity: 0.08 },
  lg: { y: 8, blur: 16, spread: -2, opacity: 0.1 },
  xl: { y: 16, blur: 32, spread: -4, opacity: 0.12 },
};

/**
 * Generate shadow tokens from seeds
 */
export function generateShadowTokens(
  seeds: ShadowSeeds = DEFAULT_SHADOW_SEEDS
): ShadowTokens {
  const intensityMult = SHADOW_INTENSITY_MULTIPLIERS[seeds.intensity];
  const blurMult = seeds.blurStyle === 'sharp' ? 0.5 : 1;

  // If intensity is none, return transparent shadows
  if (intensityMult === 0) {
    return {
      shadowXs: 'none',
      shadowSm: 'none',
      shadowMd: 'none',
      shadowLg: 'none',
      shadowXl: 'none',
    };
  }

  const generateShadow = (def: typeof BASE_SHADOWS.xs): string => {
    const y = Math.round(def.y * intensityMult);
    const blur = Math.round(def.blur * blurMult);
    const spread = def.spread;
    const opacity = (def.opacity * intensityMult).toFixed(2);

    if (seeds.colorStyle === 'tinted') {
      // Use primary color with opacity
      return `0 ${y}px ${blur}px ${spread}px oklch(from var(--color-primary) l c h / ${opacity})`;
    } else {
      // Neutral black
      return `0 ${y}px ${blur}px ${spread}px rgba(0, 0, 0, ${opacity})`;
    }
  };

  return {
    shadowXs: generateShadow(BASE_SHADOWS.xs),
    shadowSm: generateShadow(BASE_SHADOWS.sm),
    shadowMd: generateShadow(BASE_SHADOWS.md),
    shadowLg: generateShadow(BASE_SHADOWS.lg),
    shadowXl: generateShadow(BASE_SHADOWS.xl),
  };
}

/**
 * Generate shadow CSS variables
 */
export function generateShadowCSS(
  tokens: ShadowTokens,
  indent: string = '  '
): string[] {
  return [
    '',
    `${indent}/* =========================================================`,
    `${indent} * Shadow Scale`,
    `${indent} * ========================================================= */`,
    '',
    `${indent}--shadow-xs: ${tokens.shadowXs};`,
    `${indent}--shadow-sm: ${tokens.shadowSm};`,
    `${indent}--shadow-md: ${tokens.shadowMd};`,
    `${indent}--shadow-lg: ${tokens.shadowLg};`,
    `${indent}--shadow-xl: ${tokens.shadowXl};`,
  ];
}

// =============================================================================
// Motion Tokens (Deterministic - No Seeds)
// =============================================================================

/**
 * Get motion tokens (static, no generation needed)
 */
export function getMotionTokens(): MotionTokens {
  return MOTION_TOKENS;
}

/**
 * Generate motion CSS variables
 */
export function generateMotionCSS(
  tokens: MotionTokens = MOTION_TOKENS,
  indent: string = '  '
): string[] {
  return [
    '',
    `${indent}/* =========================================================`,
    `${indent} * Motion`,
    `${indent} * ========================================================= */`,
    '',
    `${indent}--duration-fast: ${tokens.durationFast};`,
    `${indent}--duration-normal: ${tokens.durationNormal};`,
    `${indent}--duration-slow: ${tokens.durationSlow};`,
    '',
    `${indent}--ease-default: ${tokens.easeDefault};`,
    `${indent}--ease-in: ${tokens.easeIn};`,
    `${indent}--ease-out: ${tokens.easeOut};`,
    `${indent}--ease-bounce: ${tokens.easeBounce};`,
  ];
}

// =============================================================================
// Combined Foundation Generation
// =============================================================================

export interface FoundationSeeds {
  typography?: TypographySeeds;
  shadow?: ShadowSeeds;
}

/**
 * Generate all foundation tokens from seeds
 */
export function generateFoundationTokens(
  seeds: FoundationSeeds = {}
): FoundationTokens {
  return {
    typography: generateTypographyTokens(seeds.typography),
    shadow: generateShadowTokens(seeds.shadow),
    motion: getMotionTokens(),
  };
}

/**
 * Generate all foundation CSS variables
 */
export function generateFoundationCSS(
  tokens: FoundationTokens,
  indent: string = '  '
): string[] {
  return [
    ...generateTypographyCSS(tokens.typography, indent),
    ...generateShadowCSS(tokens.shadow, indent),
    ...generateMotionCSS(tokens.motion, indent),
  ];
}
